// Mocks generated by Mockito 5.0.13 from annotations
// in eksimsi_tdd_clean_architecture/test/features/debe/domain/usecases/get_debe_header_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:eksimsi_tdd_clean_architecture/core/error/failures.dart' as _i5;
import 'package:eksimsi_tdd_clean_architecture/features/debe/domain/entities/debe_header.dart'
    as _i6;
import 'package:eksimsi_tdd_clean_architecture/features/debe/domain/repositories/debe_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [DebeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDebeRepository extends _i1.Mock implements _i3.DebeRepository {
  MockDebeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.DebeHeader>>> getDebeHeaders() =>
      (super.noSuchMethod(Invocation.method(#getDebeHeaders, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.DebeHeader>>>.value(
                      _FakeEither<_i5.Failure, List<_i6.DebeHeader>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.DebeHeader>>>);
  @override
  String toString() => super.toString();
}
