// Mocks generated by Mockito 5.0.15 from annotations
// in eksimsi_tdd_clean_architecture/test/features/agenda/presentation/blocs/entries_page_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:eksimsi_tdd_clean_architecture/core/error/failures.dart' as _i6;
import 'package:eksimsi_tdd_clean_architecture/features/agenda/domain/entities/entries_page.dart'
    as _i7;
import 'package:eksimsi_tdd_clean_architecture/features/agenda/domain/repositories/agenda_repository.dart'
    as _i2;
import 'package:eksimsi_tdd_clean_architecture/features/agenda/domain/usecases/get_agenda_entries_page.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAgendaRepository_0 extends _i1.Fake implements _i2.AgendaRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetAgendaEntriesPage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAgendaEntriesPage extends _i1.Mock
    implements _i4.GetAgendaEntriesPage {
  MockGetAgendaEntriesPage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AgendaRepository get agendaRepository =>
      (super.noSuchMethod(Invocation.getter(#agendaRepository),
          returnValue: _FakeAgendaRepository_0()) as _i2.AgendaRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.EntriesPage>> call(
          String? url, int? page) =>
      (super.noSuchMethod(Invocation.method(#call, [url, page]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.EntriesPage>>.value(
              _FakeEither_1<_i6.Failure, _i7.EntriesPage>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.EntriesPage>>);
  @override
  String toString() => super.toString();
}
