// Mocks generated by Mockito 5.0.15 from annotations
// in eksimsi_tdd_clean_architecture/test/features/channels/domain/entities/channel_header_test.dart.
// Do not manually edit this file.

import 'package:eksimsi_tdd_clean_architecture/features/channels/domain/entities/channel_header.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ChannelHeader].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelHeader extends _i1.Mock implements _i2.ChannelHeader {
  MockChannelHeader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get title =>
      (super.noSuchMethod(Invocation.getter(#title), returnValue: '')
          as String);
  @override
  String get subTitle =>
      (super.noSuchMethod(Invocation.getter(#subTitle), returnValue: '')
          as String);
  @override
  String get href =>
      (super.noSuchMethod(Invocation.getter(#href), returnValue: '') as String);
  @override
  String toString() => super.toString();
}
